package servers;

/**
 * Constants
 */
public enum Constants{
    GET_ALL_SENSORS_READING_FOR_THE_STATION,
    GET_NUMBER_OF_SENSORS_FOR_THE_STATION,
    GET_POWER_STATION_NAME_FOR_THE_STATION,
    REMOVE_SENSOR_FROM_THE_STATION,
    GET_ALL_IDS,
    BEGIN_OF_MESSAGE_STREAM,
    END_OF_MESSAGE_STREAM,
    GET_THE_I_TH_SENSOR_FROM_THE_STATION,
    SET_THE_MAX_VALUE_OF_I_TH_SENSOR_OF_THE_STATION
}